### ISSUE TITLE
Unable to import the library into a project

### ISSUE THREAD

**Issue by nicolasfara** [taks/esp32-nimble#3]
Hi,

I have some problems importing this library into my project.

```toml
[package]
name = "esp32-bluetooth-firmware"
version = "0.1.0"
authors = ["Nicolas Farabegoli <nicolas.farabegoli@gmail.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
esp32-nimble = "0.0.5"

[dev-dependencies]
esp-idf-sys = { version = "0.32.1", features = ["native", "binstart"] }

[build-dependencies]
embuild = "0.30.4"
```

Building the hello world:

```rust
use esp_idf_sys as _; // If using the `binstart` feature of `esp-idf-sys`, always keep this module imported

fn main() {
    // It is necessary to call this function once. Otherwise some patches to the runtime
    // implemented by esp-idf-sys might not link properly. See https://github.com/esp-rs/esp-idf-template/issues/71
    esp_idf_sys::link_patches();

    println!("Hello, world!");
}
```

I get the following errors: https://pastebin.com/YUhcS7Xm

Am I missing something? How can I import the library correctly?

Thanks!
